version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  helloworld:
    lang: ruby-http
    handler: ./helloworld
    image: koffeinfrei/helloworld:latest
  hello-crystal-http:
    lang: crystal-http
    handler: ./hello-crystal-http
    image: koffeinfrei/hello-crystal-http:latest
